/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.text.DefaultFormatterFactory;
//import javax.swing.text.MaskFormatter;
import org.joda.time.LocalDate;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;
import revisao.BuscaRevisaoDaBase;

/**
 *
 * @author f7057419
 */
public class frmCse extends javax.swing.JFrame {

    /**
     * Creates new form frmRevisãoDaBase
     */
    
    
    public frmCse() {
        initComponents();
      //  txtChave.setText(System.getProperty("user.name").toUpperCase());
        
        LocalDate hoje = new LocalDate();
        LocalDate hojeMenosDez = hoje.minusDays(10);
        DateTimeFormatter fmt = DateTimeFormat.forPattern("dd/MM/YYYY");
     
        //System.out.println(""+txtDataInicio.getText().substring(6, 10)+"-"+txtDataInicio.getText().substring(3, 5)+"-"+txtDataInicio.getText().substring(0, 2)+"");
        Color corDoformulario = new Color(255, 255, 255);
        
        
       // System.out.println(corDoformulario);
                
        Color CorDaBase=new Color(1,2,1);
        
        getContentPane().setBackground(corDoformulario); //Aqui o método chave
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setBounds(600, 400, 605, 550);
        txtSenha.requestFocus();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtChave = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Chave:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 82, 29);

        txtChave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtChave.setForeground(new java.awt.Color(0, 102, 204));
        txtChave.setText("F4114509");
        txtChave.setBorder(null);
        txtChave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChaveKeyReleased(evt);
            }
        });
        jPanel1.add(txtChave);
        txtChave.setBounds(120, 30, 120, 35);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Senha:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 30, 82, 29);

        txtSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(0, 102, 204));
        txtSenha.setText("4512451336");
        txtSenha.setToolTipText("");
        txtSenha.setBorder(null);
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenha);
        txtSenha.setBounds(410, 30, 130, 35);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 100, 580, 90);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/bb_logo.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(510, 10, 61, 61);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/SAIRM.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 280, 61, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/nome.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 490, 280, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 290, 160, 60);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 70, 410, 10);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 51));
        jLabel10.setText("CSE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(130, 10, 100, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtChaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChaveKeyReleased
        // TODO add your handling code here:
        int size = txtChave.getText().length();
        if (size == 8) {
            txtSenha.requestFocus();
        }
        if (size > 8) {
            txtChave.setText(txtChave.getText().substring(0, 8));
        }
    }//GEN-LAST:event_txtChaveKeyReleased

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtSenhaActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //TODO add your handling code here:
        BuscaRevisaoDaBase BH = new BuscaRevisaoDaBase(txtChave.getText(), txtSenha.getText());
        try {
            BH.capturaInfos();
        } catch (IOException | InterruptedException | ParseException | SQLException ex) {
            Logger.getLogger(frmCse.class.getName()).log(Level.SEVERE, null, ex);            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCse().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtChave;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
